allow half opening submodules from a commit
twosigma/git-meta pull request #840
Opened 2021-08-10 05:28 UTC by shijinglu

2021-08-10 13:04 UTC, novalis requested changes

2021-08-10 22:19 UTC, shijinglu commented on node/lib/cmd/open.js
> +        the paths from this commit",
make sense

2021-08-10 22:19 UTC, shijinglu commented on node/lib/cmd/open.js
> +        help:"open the submodule in .git/submodules only",
updating

2021-08-10 22:26 UTC, shijinglu commented on node/lib/cmd/open.js
> +        const index = yield repo.refreshIndex();
I think thy are the same in this case, to my understanding `repo.Index()` may return "cached" index, but repo.refreshIndex always return the fresh copy of the index.

2021-08-11 00:14 UTC, novalis approved these changes

2021-08-12 01:55 UTC, merged